### ISSUE TITLE
Attribute 'lts-13.26' missing

### ISSUE THREAD

**Issue by erikd** [input-output-hk/iohk-nix#115] opened 2019-07-03 03:36 UTC
PS is: https://github.com/input-output-hk/cardano-base/pull/28

Build log at: https://buildkite.com/input-output-hk/cardano-base/builds/63#c9b36d79-a00e-4f68-9b9c-62aa6b53203e

Error:
```
  "required": {
    "error": "attribute 'lts-13.26' missing, at /nix/store/avrzla5qcblrh9myl554s9bw24a7p737-source/default.nix:91:19"
```

No idea how to fix this.

**Comment by jbgi** [comment] 2019-07-03 06:18
@erikd the issue is partly described here https://github.com/input-output-hk/iohk-nix/blob/master/gotchas/gotcha-2.md#attribute-lts-1317-missing
For your project, a default version of `haskell.nix` is provided by `iohk-nix`.
The simplest way for now is to update `iohk-nix` in `cardano-base` via
```
nix-prefetch-git https://github.com/input-output-hk/iohk-nix | tee iohk-nix.json
```

**Comment by erikd** [comment] 2019-07-03 06:42
The problem is that I do not use Nix as part of my regular development process. Since it is not part of my regular development process, every Nix thing I have to do interrupts my development flow significantly. In addition since I don't use Nix, then it does something un-expected, I don't know how to fix it.

Would it be possible to provide the latest copy of that file (updated daily) somewhere?

**Comment by jbgi** [comment] 2019-07-03 09:06
this is a step that can be done by ci (automatic update of nix dependencies). @rvl has started an effort in this direction at https://github.com/input-output-hk/cardano-wallet/pull/419 this will probably be generalized and should solve a large part of the issues you encountered

**Comment by jbgi** [comment] 2019-07-03 12:30
@erikd in the meantime I pushed the fix on your branch.

**Comment by erikd** [comment] 2019-07-17 08:17
I think there is a similar issue in https://buildkite.com/input-output-hk/ouroboros-network/builds/2963

**Closed** 2019-08-01 00:21 UTC
